deploy.sh, site/config-static.toml
The problem was that the project was used to be called Public-Code and now it's called publicode.asia
=> fixing the github pages display

site/static/css/buttons-spread.css, site/static/css/creative.css, site/static/css/custom.css
=> Edit style

site/static/css/creative.css, site/static/css/custom.css
=> Change colours

README.md
=> Fixed Broken Links in README.md

site/layouts/partials/legal.html
Closes https://github.com/fossasia/publiccode.asia/issues/27
=> Removed Transparency from legal.html

site/languages/strings.XY.toml.sample, site/languages/strings.de.toml, site/languages/strings.en.toml, site/languages/strings.eo.toml, site/languages/strings.es.toml, site/languages/strings.fr.toml, site/languages/strings.id.toml, site/languages/strings.ms.toml, site/languages/strings.tr.toml, site/languages/strings.vi.toml, site/languages/strings.zh_tw.toml, site/layouts/partials/functions/sign-form.html, site/static/css/custom.css
Added region and organization for all languages
Closes #26
=> Added region and organization field for every language

site/content/imprint.bg.md, site/content/imprint.de.md, site/content/imprint.eo.md, site/content/imprint.es.md, site/content/imprint.fr.md, site/content/imprint.gj.md, site/content/imprint.hi.md, site/content/imprint.id.md, site/content/imprint.vi.md
imprint added, still figuring out how to make it in it's own page
=> add imprint

site/data/share/bg/1-gplus.yaml, site/data/share/de/1-gplus.yaml, site/data/share/en/1-gplus.yaml, site/data/share/eo/1-gplus.yaml, site/data/share/es/1-gplus.yaml, site/data/share/fr/1-gplus.yaml, site/data/share/gj/1-gplus.yaml, site/data/share/hi/1-gplus.yaml, site/data/share/id/1-gplus.yaml, site/data/share/ms/1-gplus.yaml, site/data/share/tl/1-gplus.yaml, site/data/share/tm/1-gplus.yaml, site/data/share/tr/1-gplus.yaml, site/data/share/vi/1-gplus.yaml, site/data/share/zh_tw/1-gplus.yaml, site/static/css/buttons-side.css, site/static/css/buttons-spread.css
=> Google+ sharing option added

site/layouts/partials/js.html
Closes #22 
Implemented google+ without redirection to fsfe.org site
=> google+ without redirection

site/layouts/partials/js.html
I copied a code of snippet that would serialize HTML forms into js objects
=> Attribute code

site/languages/strings.XY.toml.sample, site/languages/strings.bg.toml, site/languages/strings.de.toml, site/languages/strings.en.toml, site/languages/strings.eo.toml, site/languages/strings.es.toml, site/languages/strings.fr.toml, site/languages/strings.gj.toml, site/languages/strings.hi.toml, site/languages/strings.id.toml, site/languages/strings.ms.toml, site/languages/strings.tl.toml, site/languages/strings.tm.toml, site/languages/strings.tr.toml, site/languages/strings.vi.toml, site/languages/strings.zh_tw.toml, site/static/css/bootstrap.css
=> Changed euro symbol to Dollar symbol

site/static/css/bootstrap.css
Added changed hex code in bootstrap.css.
=> Added changed hex code in bootstrap.css

TRANSLATE.md, site/static/js/onScrollMenu.js
Fixes #74 
The logo now shows in all languages.
Screenshots:
Please review this ASAP :)
=> Logo shows in languages other than English too

site/build/build.sh, site/content/imprint.pl.md, site/content/openinitiative.pl.md, site/content/openinitiative/all-signatures.pl.md, site/content/openinitiative/confirm.pl.md, site/content/openinitiative/success.pl.md, site/content/privacy.pl.md, site/data/share/pl/1-gplus.yaml, site/data/share/pl/2-linkedin.yaml, site/data/share/pl/3-reddit.yaml, site/data/share/pl/4-twitter.yaml, site/data/share/pl/5-facebook.yaml, site/data/share/pl/6-support.yaml, site/languages/strings.pl.toml
**Added following Polish translations:**
- imprint
- openeinitiative
- all-signatures
- confirm
- success
- privacy
- share/all files
- strings
Also added "pl" into build.sh
=> Polish translation added Fixes #69

site/layouts/partials/start.html, site/layouts/partials/sub-pages/navbar.html, site/static/js/onScrollMenu.js
Fixes #93. Logos on all pages should work fine now.
Changes made:
1. I've changed the path of the images according to the route, which was giving a 404 earlier.
2. I've changed the image name from logo_header.svg to logo.svg to maintain uniformity
Please review the PR :)
=> Logo bugs have been fixed

site/layouts/partials/js.html, site/layouts/partials/spread.html, site/static/css/custom.css
Fixes #109 
Changes made:
1. The close button bug has been fixed. It was due to a typo.
2. The Paypal div look has been improved, by giving padding appropriately.
Please review 😄
=> Close button works and improved look of Paypal div

CONTRIBUTING.md, README.md
Added Documentation regarding Contributor Best Practices
Fixes #113
=> Fixes #113: Added Documentation regarding Contributor Best Practices

donate.html, script.js, site/layouts/partials/spread.html, style.css
This will be a preview of how to change the donation form, it needs work though.
=> Test new donation form

.travis.yml
Fixes #129 
Added Cache to travis.yml
=> Fixes #129 : Added Caching to Travis CI

site/static/css/custom.css
Adds z-index property to #action-box which states how may signatures are
made for publiccode initiative to fix the box hiding problem in the
supporting organizations section
Fixes #142
=> Fixes #142: Adds z-index to signatures pop-up
